[font]
normal = { family = "Cascadia Mono" }
bold = { family = "Cascadia Mono", style = "Bold" }
italic = { family = "Cascadia Mono", style = "Italic" }
bold_italic = { family = "Cascadia Mono", style = "Bold Italic" }
size = 16
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }
builtin_box_drawing = true
