gaps:
  # Gap between adjacent windows.
  inner_gap: "16px"
  # Gap between windows and the screen edge.
  outer_gap: "16px"
# Highlight active/inactive windows with a colored border.

# ** Exclusive to Windows 11 due to API limitations.
focus_borders:
  active:
    enabled: true
    color: "#0092FE"
  inactive:
    enabled: false
    color: "#ff0000"
bar:
  height: "50px"
  position: "top"
  opacity: 1
  background: "#070219E6"
  foreground: "#27fbfe"
  font_family: "CozetteVector"
  font_size: "22"
  padding: "0 8px 0px 8px"
  offset_x: "16px"
  offset_y: "16px"
  border_radius: "0px"
  border_width: "1px"
  border_color: "#0092FE"
  component_separator:
    label: ""
  components_left:
    - type: "workspaces"
      margin: "0 4px"
      padding: "0"
      # font_size: "18"
      focused_workspace_background: "transparent"
      focused_workspace_foreground: "#fb4934"
      default_workspace_background: "transparent"
      default_workspace_foreground: "#27fbfe"
      displayed_workspace_background: "#fb4934"
      displayed_workspace_foreground: "#fb4934"
      # - type: "music"
  #   label_not_playing: "no music"

  #   label_paused: "{song_title} - {artist_name}"

  #   label_playing: "{song_title} - {artist_name} ▶"

  #   max_title_length: 20

  #   max_artist_length: 20
  components_center:
    - type: "window title"
  components_right:
    # - type: "system tray"

    #   margin: "0 0px"

    #   padding: "7px 0"

    #   label_expand_text: " "

    #   label_collapse_text: " "
    - type: "cpu"
      label: "<attr fs='21' fg='#fb007a'>❤</attr> {percent_usage}%"
      margin: "0 14px 0 0px"
      # How often this counter is refreshed.

      refresh_interval_ms: 1000
    - type: "memory"
      label: "<attr fs='19' fg='#b8bb26' >✂</attr> {percent_usage}%"
      margin: "0 4px"
      # How often this counter is refreshed.

      refresh_interval_ms: 1000
    - type: "gpu"
      label: "<attr fs='19' fg='#8ec07c'>⛨</attr> {percent_usage}%"
      margin: "0 13px"
      # How often this counter is refreshed.

      refresh_interval_ms: 1000
    - type: "volume"
      label_low: "<attr fs='21' fg='#83a598'>⏼</attr> {volume_level}%"
      label_medium: "<attr fs='21' fg='#83a598'>◎</attr> {volume_level}%"
      label_high: "<attr fs='21' fg='#83a598'>◎</attr> {volume_level}%"
      label_mute: "<attr fs='21' fg='#fb4934'>⌀</attr><attr fg='#fb4934'> {volume_level}%</attr>"
      margin: "0 16px 0 2px"
    - type: "battery"
      label_draining: "<attr fg='#fabd2f' fs='21'>⌛</attr> {battery_level}% "
      label_power_saver: "<attr fs='21' fg='#fb4934'>☠</attr><attr fg='#fb4934'> {battery_level}%</attr>"
      label_charging: "<attr fs='21' fg='#fabd2f'>⚡</attr> {battery_level}% "
      margin: "0 0 0 0px"
    - type: "network"
      label_no_internet: "<attr fg='#fb4934' fs='21'>✘</attr>"
      label_ethernet: "<attr fs='22'></attr>"
      label_wifi_strength_0: "WiFi: 0%"
      label_wifi_strength_25: "WiFi: 25%"
      label_wifi_strength_50: "WiFi: 50%"
      label_wifi_strength_75: "WiFi: 75%"
      label_wifi_strength_100: "WiFi: 100%"
      margin: "0 0px 0 20px"
    - type: "tiling direction"
      label_horizontal: "<attr fs='21'> ⏵ </attr>"
      label_vertical: "<attr fs='21'> ⏷ </attr>"
      # background: "#ffffff33"

      margin: "0 px"
      # padding: "4px 4px"
    #   margin: "0 14px"
    - type: "clock"
      # Documentation on formatting date/time string:

      #   background: "#ffffff33"

      # - type: "binding mode"

      # https://learn.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings
      time_formatting: " HH:mm dddd, dd/MM/yyyy"
      margin: "0 6px 0 6px"
