[font]
normal = { family = "CaskaydiaCove Nerd Font Mono" }
bold = { family = "CaskaydiaCove Nerd Font Mono", style = "Bold" }
italic = { family = "CaskaydiaCove Nerd Font Mono", style = "Italic" }
bold_italic = { family = "CaskaydiaCove Nerd Font Mono", style = "Bold Italic" }
size = 15
offset = { x = 1, y = 0 }
glyph_offset = { x = 0, y = 0 }
builtin_box_drawing = true
