[colors.primary]
background = "#0d1017"
foreground = "#bfbdb6"
dim_foreground = "#3b414a"
bright_foreground = "#626975"

[colors.cursor]
text = "#bfbdb6"
cursor = "#53bdfa"

[colors.vi_mode_cursor]
text = "#bfbdb6"
cursor = "#7fd962"

[colors.search.matches]
foreground = "#bfbdb6"
background = "#f07178"

[colors.search.focused_match]
foreground = "#bfbdb6"
background = "#7fd962"

[colors.footer_bar]
foreground = "#bfbdb6"
background = "#53bdfa"

[colors.hints.start]
foreground = "#bfbdb6"
background = "#ffb454"

[colors.hints.end]
foreground = "#bfbdb6"
background = "#ffb454"

[colors.selection]
text = "#bfbdb6"
background = "#d2a6ff"

[colors.normal]
black = "#636a72"
red = "#f07178"
green = "#7fd962"
yellow = "#ffb454"
blue = "#53bdfa"
magenta = "#d2a6ff"
cyan = "#95e6cb"
white = "#bfbdb6"

[colors.bright]
black = "#636a72"
red = "#f07178"
green = "#aad94c"
yellow = "#ffb454"
blue = "#53bdfa"
magenta = "#d2a6ff"
cyan = "#95e6cb"
white = "#bfbdb6"

[colors.dim]
black = "#636a72"
red = "#f07178"
green = "#7fd962"
yellow = "#ffb454"
blue = "#53bdfa"
magenta = "#d2a6ff"
cyan = "#95e6cb"
white = "#bfbdb6"

[[colors.indexed_colors]]
index = 16
color = "#53bdfa"

[[colors.indexed_colors]]
index = 17
color = "#53bdfa"
