general:
  # Whether to automatically focus windows underneath the cursor.
  focus_follows_cursor: false

  # Whether to jump the cursor between windows focused by the WM.
  cursor_follow_focus: true

  # Whether to switch back and forth between the previously focused workspace
  # when focusing the current workspace.
  toggle_workspace_on_refocus: false

  # Whether to show floating windows as always on top.
  show_floating_on_top: false

  # Amount to move floating windows by (eg. when using `alt+<hjkl>` on a floating window)
  floating_window_move_amount: "5%"

  # *Strongly* recommended to set to 'false'. Whether to globally enable/disable
  # window transition animations (on minimize, close, etc). Set to 'unchanged'
  # to make no setting changes.
  window_animations: "false"

gaps:
  # Gap between adjacent windows.
  inner_gap: "8px"

  # Gap between windows and the screen edge.
  outer_gap: "8px"

# Highlight active/inactive windows with a colored border.
# ** Exclusive to Windows 11 due to API limitations.
focus_borders:
  active:
    enabled: true
    color: "#FF6188"

  inactive:
    enabled: false
    color: "#ff0000"

bar:
  height: "32px"
  position: "top"
  opacity: 1
  background: "#221f22"
  foreground: "#ffffff"
  font_family: "CaskaydiaCove Nerd Font Mono"
  font_size: "13px"
  padding: "4px 8px"
  offset_x: "8px"
  offset_y: "8px"
  border_radius: "8px"
  component_separator:
    label: "  "
  components_left:
    - type: "workspaces"
      margin: "0 8px"
      padding: "0"
      font_size: "21"
      focused_workspace_background: "transparent"
      focused_workspace_foreground: "#FF6188"
      displayed_workspace_background: "#00000033"
      default_workspace_background: "transparent"

    - type: "cpu"
      label: "<attr fs='25' fg='#FF6188'></attr> {percent_usage}%"
      margin: "0 8px"
      # How often this counter is refreshed.
      refresh_interval_ms: 1000

    - type: "memory"
      label: "<attr fs='24' fg='#A9DC76'></attr> {percent_usage}%"
      margin: "0 8px"
      # How often this counter is refreshed.
      refresh_interval_ms: 1000

    - type: "gpu"
      label: "<attr fs='32' fg='#AB9DF2'>󰾲</attr> {percent_usage}%"
      margin: "0 8px"
      # How often this counter is refreshed.
      refresh_interval_ms: 1000

    - type: "volume"
      label_low: "<attr fs='30' fg='#78DCE8'></attr> {volume_level}%"
      label_medium: "<attr fs='30' fg='#78DCE8'></attr> {volume_level}%"
      label_high: "<attr fs='30' fg='#78DCE8'></attr> {volume_level}%"
      label_mute: "<attr fs='30' fg='#FF6188'>󰝟</attr>"
      margin: "0 8px"

    - type: "battery"
      label_draining: "<attr fg='#FFD866'>󰁽</attr> {battery_level}%"
      label_power_saver: "<attr fs='25' fg='#FFD866'></attr> {battery_level}% (power saver)"
      label_charging: "<attr fg='#FFD866'>󱐋</attr> {battery_level}%"
      margin: "0 8px"

  components_center:
    - type: "window title"

  components_right:

    # - type: "tiling direction"
    #   label_horizontal: "⮂"
    #   label_vertical: "⮁"
    #   background: "#ffffff33"
    #   margin: "0 8px"
    #   padding: "4px 4px"

    # - type: "system tray"
    #   margin: "0 8px"
    #   padding: "4px 0"
    #   label_expand_text: " < "
    #   label_collapse_text: " > "

    # - type: "binding mode"
    #   background: "#ffffff33"
    #   margin: "0 8px"

    - type: "clock"
      # Documentation on formatting date/time string:
      # https://learn.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings
      time_formatting: " HH:mm dddd, dd/MM/yyyy"
      margin: "0 8px"

workspaces:
  - name: "1"
    # Optional override for the workspace label in the bar. Does not need to be unique.
    display_name: ""

    # Optionally force the workspace on a specific monitor if it exists. Use the monitor's number
    # as shown in the Windows display settings (eg. 1, 2, 3...).
    # bind_to_monitor: 1

    # Optionally prevent workspace from being deactivated when empty.
    # keep_alive: true

  - name: "2"
    display_name: ""
    # keep_alive: true
  - name: "3"
    display_name: "󱃖"
    # keep_alive: true
  - name: "4"
    display_name: "󱧶"
    # keep_alive: true
  - name: "5"
    display_name: "󰙯"
    # keep_alive: true
  - name: "6"
    display_name: ""
    # keep_alive: true
  - name: "7"
    display_name: ""
    # keep_alive: true
  - name: "8"
    display_name: ""
    # keep_alive: true
  - name: "9"
    display_name: ""
    # keep_alive: true

window_rules:
  # Task Manager requires admin privileges to manage and should be ignored unless running
  # the WM as admin.
  # - command: "ignore"
  #   match_process_name: "/Taskmgr|ScreenClippingHost/"

  # Launches system dialogs as floating by default (eg. File Explorer save/open dialog).
  - command: "set floating"
    match_class_name: "#32770"

  # Some applications (eg. Steam) have borders that extend past the normal border size.
  - command: "resize borders 0px -7px -7px -7px"
    match_process_name: "steam"

  # Terminal workspace
  - commands: ["move to workspace 1", "focus workspace 1"]
    match_process_name: "WindowsTerminal"

  # Browser workspace
  # Command to run. Use `commands` to specify an array of commands to run in sequence.
  - commands: ["move to workspace 2", "focus workspace 2"]
    # Process name to match exactly.
    match_process_name: "chrome"
    # Window title to match exactly.
    # match_title: "/.*/"
    # Class name to match exactly.
    # match_class_name: "Chrome_WidgetWin_1"

  # Code workspace
  - commands: ["move to workspace 3", "focus workspace 3"]
    match_process_name: "Code"

  # Folder and files workspace
  - commands: ["move to workspace 4", "focus workspace 4"]
    match_process_name: "explorer"

  # Discord workspace
  - commands: ["move to workspace 5", "focus workspace 5"]
    match_process_name: "Discord"

  # Settings workspace
  - commands: ["move to workspace 6", "focus workspace 6"]
    match_process_name: "Taskmgr"
  - commands: ["move to workspace 6", "focus workspace 6"]
    match_title: "Settings"

  # Others workspace
  - commands: ["move to workspace 7"]
    match_process_name: "GoogleDriveFS"

binding_modes:
  # - name: "resize"
  #   keybindings:
      # Resize focused window by a percentage or pixel amount.
      # - command: "resize width -2%"
      #   bindings: ["H", "Left"]
      # - command: "resize width +2%"
      #   bindings: ["L", "Right"]
      # - command: "resize height +2%"
      #   bindings: ["K", "Up"]
      # - command: "resize height -2%"
      #   bindings: ["J", "Down"]
      # Press enter/escape to return to default keybindings.
      # - command: "binding mode none"
      #   bindings: ["Escape", "Enter"]

keybindings:
  # Shift focus in a given direction.
  - command: "focus left"
    bindings: ["Alt+H"]
  - command: "focus right"
    bindings: ["Alt+L"]
  - command: "focus up"
    bindings: ["Alt+K"]
  - command: "focus down"
    bindings: ["Alt+J"]

  # Move focused window in a given direction.
  - command: "move left"
    bindings: ["Alt+Shift+H"]
  - command: "move right"
    bindings: ["Alt+Shift+L"]
  - command: "move up"
    bindings: ["Alt+Shift+K"]
  - command: "move down"
    bindings: ["Alt+Shift+J"]

  # Resize focused window by a percentage or pixel amount.
  - command: "resize width -2%"
    binding: "Alt+U"
  - command: "resize width +2%"
    binding: "Alt+P"
  - command: "resize height +2%"
    binding: "Alt+O"
  - command: "resize height -2%"
    binding: "Alt+I"

  # As an alternative to the resize keybindings above, resize mode enables resizing via
  # HJKL or arrow keys. The binding mode is defined above with the name "resize".
  # - command: "binding mode resize"
  #   binding: "Alt+R"

  # Change tiling direction. This determines where new tiling windows will be inserted.
  - command: "tiling direction toggle"
    binding: "Alt+D"

  # Change focus between floating / tiling windows.
  - command: "focus mode toggle"
    binding: "Alt+Shift+F"

  # Change the focused window to be floating / tiling.
  - command: "toggle floating"
    binding: "Alt+F"

  # Change the focused window to be maximized / unmaximized.
  - command: "toggle maximized"
    binding: "Alt+M"

  # Minimize focused window.
  # - command: "set minimized"
  #   binding: "Alt+N"

  # Close focused window.
  - command: "close"
    binding: "Alt+W"

  # Kill GlazeWM process safely.
  - command: "exit wm"
    binding: "Alt+Ctrl+Shift+W"

  # Re-evaluate configuration file.
  - command: "reload config"
    binding: "Alt+Shift+R"

  # Launch CMD terminal (alternatively `exec wt` or `exec %ProgramFiles%/Git/git-bash.exe`
  # to start Windows Terminal and Git Bash respectively.
  - command: "exec wt"
    binding: "Alt+Enter"

  # Focus the workspace that last had focus.
  # - command: "focus workspace recent"
  #   binding: "Alt+Y"

  # Focus the next/previous workspace defined in `workspaces` config.
  # - command: "focus workspace next"
  #   binding: "Alt+T"
  # - command: "focus workspace prev"
  #   binding: "Alt+Shift+T"

  # Change focus to a workspace defined in `workspaces` config.
  - command: "focus workspace 1"
    binding: "Alt+1"
  - command: "focus workspace 2"
    binding: "Alt+2"
  - command: "focus workspace 3"
    binding: "Alt+3"
  - command: "focus workspace 4"
    binding: "Alt+4"
  - command: "focus workspace 5"
    binding: "Alt+5"
  - command: "focus workspace 6"
    binding: "Alt+6"
  - command: "focus workspace 7"
    binding: "Alt+7"
  - command: "focus workspace 8"
    binding: "Alt+8"
  - command: "focus workspace 9"
    binding: "Alt+9"

  # Move focused workspace to a monitor in a given direction.
  # - command: "move workspace left"
  #   binding: "Alt+A"
  # - command: "move workspace right"
  #   binding: "Alt+F"
  # - command: "move workspace up"
  #   binding: "Alt+D"
  # - command: "move workspace down"
  #   binding: "Alt+S"

  # Move focused window to a workspace defined in `workspaces` config.
  - commands: ["move to workspace 1", "focus workspace 1"]
    binding: "Alt+Shift+1"
  - commands: ["move to workspace 2", "focus workspace 2"]
    binding: "Alt+Shift+2"
  - commands: ["move to workspace 3", "focus workspace 3"]
    binding: "Alt+Shift+3"
  - commands: ["move to workspace 4", "focus workspace 4"]
    binding: "Alt+Shift+4"
  - commands: ["move to workspace 5", "focus workspace 5"]
    binding: "Alt+Shift+5"
  - commands: ["move to workspace 6", "focus workspace 6"]
    binding: "Alt+Shift+6"
  - commands: ["move to workspace 7", "focus workspace 7"]
    binding: "Alt+Shift+7"
  - commands: ["move to workspace 8", "focus workspace 8"]
    binding: "Alt+Shift+8"
  - commands: ["move to workspace 9", "focus workspace 9"]
    bindings: ["Alt+Shift+9"]
